# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpstan@v3
      with:
          path: src/
          
    - name: start mysql
      run: sudo /etc/init.d/mysql start

    - name: Create test database
      run: mysql -uroot -proot < data/sql/db_test.sql
      
    - name: generate jwt test keys priv
      run: openssl genrsa -out config/jwt/private-test.pem -aes256 4096
      
    - name: generate jwt test keys pub
      run: openssl rsa -pubout -in config/jwt/private-test.pem -out config/jwt/public-test.pem
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: mysql://root:root@127.0.0.1:3306/nkcs?serverVersion=5.7
        JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private-test.pem"
        JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public-test.pem"
        JWT_PASSPHRASE: 4a6efcc52d3a785113cb4caab67bc3417209613a4e9114ae3104dafc792a63d7
        
      run: vendor/bin/phpunit
